changing the yam

diff --git a/.github/workflows/assignment_wordle-api-web.yml b/.github/workflows/assignment_wordle-api-web.yml
--- a/.github/workflows/assignment_wordle-api-web.yml
+++ b/.github/workflows/assignment_wordle-api-web.yml
@@ -1,12 +1,16 @@
 # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
 # More GitHub Actions for Azure: https://github.com/Azure/actions
 
-name: Build and deploy ASP.Net Core app to Azure Web App - wordle-api-web
+name: Build and deploy ASP.Net Core app to Azure Web App - WordleApiClass
 
 on:
   push:
     branches:
-      - Assignment*
+      - main
+      - 'Assignment*'
+    paths:
+      - 'Wordle.Api/**'
+      - '.github/workflows/main_wordleapiclass.yml'
   workflow_dispatch:
 
 jobs:
@@ -21,9 +25,35 @@ jobs:
         with:
           dotnet-version: '6.0.x'
           include-prerelease: true
-
+                
+      - name: Set up dependency caching for faster builds
+        uses: actions/cache@v3
+        with:
+          path: ~/.nuget/packages
+          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-nuget-
       - name: Build with dotnet
         run: dotnet build --configuration Release
+        
+      - name: Test with dotnet
+        run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-restore
+        
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: .NET Tests            # Name of the check run which will be created
+          path: '**/test-results.trx'    # Path to test results
+          reporter: dotnet-trx        # Format of test results
+
+      - name: Upload Test TRX file
+        uses: actions/upload-artifact@v2  # upload test results
+        continue-on-error: true       # if there are no test results, this should still pass.
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: dotnet-trx
+          path: '**/test-results.trx'
 
       - name: dotnet publish
         run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
@@ -37,6 +67,7 @@ jobs:
   deploy:
     runs-on: windows-latest
     needs: build
+    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
     environment:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
@@ -51,7 +82,7 @@ jobs:
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v2
         with:
-          app-name: 'wordle-api-web'
+          app-name: 'WordleApiClass'
           slot-name: 'Production'
-          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EC13E0D574784862B7B8B8BA7947E22A }}
+          publish-profile: ${{ secrets.API_AZUREAPPSERVICE_PUBLISHPROFILE }}
           package: .
